### ISSUE TITLE
运行失败：meth.py代码错误

### ISSUE THREAD

**Issue by nightlye** [UnAbuse/reptile.inclued#5]
![image](https://user-images.githubusercontent.com/53067795/224610340-988e7984-7c1a-491a-ba1e-4fef245b283b.png)
运行环境是谷歌Colaboratory

**Comment by UnAbuse** [comment]
这是python版本兼容问题，match-case是3.10版本后支持的语法

**Comment by UnAbuse** [comment]
我后面会写向下兼容的代码
