### ISSUE TITLE
您好，运行FanQieNovelReptile.py出现问题

### ISSUE THREAD

**Issue by SakurajimaChen** [UnAbuse/reptile.inclued#6]
File "C:\Users\ainil\Desktop\reptile.inclued-main\reptile\FanQieNovelReptile.py", line 8, in <module>
    from reptile.packet import *
ModuleNotFoundError: No module named 'reptile.packet'
已使用pip 安装 reptile 这个包
问题仍然出现

**Comment by UnAbuse** [comment]
> fanqie.direct('7077516958534470656') fanqie.content("7160102911857394191") 这两条命令均出错 希望能修复 感谢

已经修复这个问题

**Comment by UnAbuse** [comment]
> File "C:\Users\ainil\Desktop\reptile.inclued-main\reptile\FanQieNovelReptile.py", line 8, in from reptile.packet import * ModuleNotFoundError: No module named 'reptile.packet' 已使用pip 安装 reptile 这个包 问题仍然出现

请遵循目录结构：

‘’‘
--folder
 -reptile
 -app.py
’‘’

reptile为项目下reptile文件夹，请保证文件夹与app.py在同一目录下

**Comment by shusheng110** [comment]
> > fanqie.direct('7077516958534470656') fanqie.content("7160102911857394191") 这两条命令均出错 希望能修复 感谢
> 
> 已经修复这个问题

感谢大佬 速度真快 我抓包研究了一天了还是没能抓包

**Comment by EliasMercer** [comment]
> > File "C:\Users\ainil\Desktop\reptile.inclued-main\reptile\FanQieNovelReptile.py", line 8, in from reptile.packet import * ModuleNotFoundError: No module named 'reptile.packet' 已使用pip 安装 reptile 这个包 问题仍然出现
> 
> 请遵循目录结构：
> 
> --folder -reptile -app.py
> 
> reptile为项目下reptile文件夹，请保证文件夹与app.py在同一目录下

这个app.py需要自己构造吗

**Comment by UnAbuse** [comment]
> > > File "C:\Users\ainil\Desktop\reptile.inclued-main\reptile\FanQieNovelReptile.py", line 8, in from reptile.packet import * ModuleNotFoundError: No module named 'reptile.packet' 已使用pip 安装 reptile 这个包 问题仍然出现
> > 
> > 请遵循目录结构：
> > 
> > --folder -reptile -app.py
> > 
> > reptile为项目下reptile文件夹，请保证文件夹与app.py在同一目录下
> 
> 这个app.py需要自己构造吗

是的，需要自己构造

**Comment by EliasMercer** [comment]
> > > > 文件 “C：\Users\ainil\Desktop\reptile.inclued-main\reptile\FanQieNovelReptile.py”，第 8 行，来自 reptile.packet import * ModuleNotFoundError： 没有名为 'reptile.packet' 的模块 已使用pip 安装 reptile 这个包 问题仍然出现
> > > 
> > > 
> > > 请遵循目录结构：
> > > --文件夹 -爬行动物 -app.py
> > > reptile为项目下reptile文件夹，请保证文件夹与 app.py 在同一目录下
> > 
> > 
> > 这个 app.py 需要自己构造吗
> 
> 是的，需要自己构造

请问一下该怎么做，不懂这些
